apiVersion: sfmesh.k8s.io/v1alpha1
kind: Application
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: applicationsam
spec:
  # Add fields here
  services:
    - name: "myyservice"
      replicaCount: 1
      description: "Awesome Service"
      osType: Linux
      codePackages:
        - name: helloWorldCode
          image: "seabreeze/sbz-helloworld:1.0-alpine"
          endpoints:
            - name: "helloworld"
              port: 80
  description: "something"
  location: "eastus"
  resourceGroup: "default"
