apiVersion: sfmesh.k8s.io/v1alpha1
kind: Application
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: application-sample
spec:
  # Add fields here
  osType: Linux
  codePackages:
    - name: helloWorldCode
      image: "seabreeze/sbz-helloworld:1.0-alpine"
      endpoints:
        - name: "helloworld"
          port: 80
      resources:
        requests:
          memoryInGB: 1
          cpu: 1
  description: "something"
  location: "eastus"
  resourceGroup: "default"
